namespace CassieReplacement.Reader.Models.Enums
{
    public enum DamageTypeEnumToInt
    {
        None = 0,
        Tesla = 1,
        Warhead = 2,
        Decontamination = 3,
        Player = 4,
        Unknown = 5,
        Falldown = Unknown,
        Asphyxiation = Unknown,
        Poison = Unknown,
        Bleeding = Unknown,
        Firearm = Player,
        MicroHid = Player,
        Scp = Player,
        Explosion = Player,
        Scp018 = Player,
        Scp207 = Unknown,
        Recontainment = Unknown,
        Crushed = Unknown,
        FemurBreaker = Unknown,
        PocketDimension = Unknown,
        FriendlyFireDetector = Unknown,
        SeveredHands = Unknown,
        SeveredEyes = Unknown,
        Custom = Unknown,
        Scp049 = Player,
        Scp096 = Player,
        Scp173 = Player,
        Scp939 = Player,
        Scp0492 = Player,
        Scp106 = Player,
        Crossvec = Player,
        Logicer = Player,
        Revolver = Player,
        Shotgun = Player,
        AK = Player,
        Com15 = Player,
        Com18 = Player,
        Fsp9 = Player,
        E11Sr = Player,
        Hypothermia,
        ParticleDisruptor = Player,
        CardiacArrest,
        Com45 = Player,
        Jailbird = Player,
        Frmg0 = Player,
        A7 = Player,
        Scp3114 = Player,
        Strangled = Player,
        Marshmallow = Player,
        Scp1507 = Player,
        Scp956 = Unknown,
        SnowBall = Player,
        Scp127 = Player,
    }
}
